### ISSUE TITLE
feature idea: mvn commitlint:check $enteredCommitMessage

### ISSUE THREAD

**Issue by Kambaa** [Rugal/commitlinter-maven-plugin#3]
In addition to getting the commit message from git and checking it, how about giving the commit message as an argument and run the action like this: 

 ```
 mvn commitlint:check ENTERED_COMMIT_MESSAGE_FILE
 mvn commitlint:check ENTERED_COMMIT_MESSAGE_TEXT
```

I'm doing a research on git hooks, and from what i understand, i can check my flyway, spotless, and checkstyle configurations on the projects via maven commands on the precommit hook, I was thinking about using this plugin, configure the plugin to do same checks which is defined [here](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#rules), and write the mvn command on the `commit-msg` git hook, tell the hook to check the commit message file directly ( or get the written message first, then validate it). With this way i don't need to add node npm yarn stuff on my maven projects.

How about it?
Thank you and have a nice day.

**Comment by Rugal** [comment]
> In addition to getting the commit message from git and checking it, how about giving the commit message as an argument and run the action like this:
> 
> ```
> mvn commitlint:check ENTERED_COMMIT_MESSAGE_FILE
> mvn commitlint:check ENTERED_COMMIT_MESSAGE_TEXT
> ```
> 
> I'm doing a research on git hooks, and from what i understand, i can check my flyway, spotless, and checkstyle configurations on the projects via maven commands on the precommit hook, I was thinking about using this plugin, configure the plugin to do same checks which is defined [here](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#rules), and write the mvn command on the `commit-msg` git hook, tell the hook to check the commit message file directly ( or get the written message first, then validate it). With this way i don't need to add node npm yarn stuff on my maven projects.
> 
> How about it? Thank you and have a nice day.



Hi, This is already done. Please check `testCommitMessage` parameter in the readme file
